"""
Shared constants for evaluation status and cause codes.
"""

# Success states
CAUSE_OK = "OK"

# Error states - Logic/Answer
CAUSE_WRONG_VALUE = "WRONG_VALUE"
CAUSE_ANSWER_NOT_FOUND = "ANSWER_NOT_FOUND"

# Error states - Runtime/System
CAUSE_CRASH = "CRASH"
CAUSE_TIMEOUT = "TIMEOUT"
CAUSE_TOKEN_BUDGET_EXCEEDED = "TOKEN_BUDGET_EXCEEDED"

# Error states - Stop Conditions 
CAUSE_REPORT_TOO_SHORT = "REPORT_TOO_SHORT"
CAUSE_MISSING_CITATION = "MISSING_CITATION"
CAUSE_MAX_STEPS_REACHED = "MAX_STEPS_REACHED"
CAUSE_STOPPED_WITH_ERRORS = "STOPPED_WITH_ERRORS"
